/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.ambiata.ivory.extract;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class FactsetLookup implements org.apache.thrift.TBase<FactsetLookup, FactsetLookup._Fields>, java.io.Serializable, Cloneable, Comparable<FactsetLookup> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("FactsetLookup");

  private static final org.apache.thrift.protocol.TField PRIORITIES_FIELD_DESC = new org.apache.thrift.protocol.TField("priorities", org.apache.thrift.protocol.TType.MAP, (short)1);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new FactsetLookupStandardSchemeFactory());
    schemes.put(TupleScheme.class, new FactsetLookupTupleSchemeFactory());
  }

  public Map<String,Short> priorities; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    PRIORITIES((short)1, "priorities");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // PRIORITIES
          return PRIORITIES;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.PRIORITIES, new org.apache.thrift.meta_data.FieldMetaData("priorities", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.MapMetaData(org.apache.thrift.protocol.TType.MAP, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING), 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I16))));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(FactsetLookup.class, metaDataMap);
  }

  public FactsetLookup() {
  }

  public FactsetLookup(
    Map<String,Short> priorities)
  {
    this();
    this.priorities = priorities;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public FactsetLookup(FactsetLookup other) {
    if (other.isSetPriorities()) {
      Map<String,Short> __this__priorities = new HashMap<String,Short>(other.priorities);
      this.priorities = __this__priorities;
    }
  }

  public FactsetLookup deepCopy() {
    return new FactsetLookup(this);
  }

  @Override
  public void clear() {
    this.priorities = null;
  }

  public int getPrioritiesSize() {
    return (this.priorities == null) ? 0 : this.priorities.size();
  }

  public void putToPriorities(String key, short val) {
    if (this.priorities == null) {
      this.priorities = new HashMap<String,Short>();
    }
    this.priorities.put(key, val);
  }

  public Map<String,Short> getPriorities() {
    return this.priorities;
  }

  public FactsetLookup setPriorities(Map<String,Short> priorities) {
    this.priorities = priorities;
    return this;
  }

  public void unsetPriorities() {
    this.priorities = null;
  }

  /** Returns true if field priorities is set (has been assigned a value) and false otherwise */
  public boolean isSetPriorities() {
    return this.priorities != null;
  }

  public void setPrioritiesIsSet(boolean value) {
    if (!value) {
      this.priorities = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case PRIORITIES:
      if (value == null) {
        unsetPriorities();
      } else {
        setPriorities((Map<String,Short>)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case PRIORITIES:
      return getPriorities();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case PRIORITIES:
      return isSetPriorities();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof FactsetLookup)
      return this.equals((FactsetLookup)that);
    return false;
  }

  public boolean equals(FactsetLookup that) {
    if (that == null)
      return false;

    boolean this_present_priorities = true && this.isSetPriorities();
    boolean that_present_priorities = true && that.isSetPriorities();
    if (this_present_priorities || that_present_priorities) {
      if (!(this_present_priorities && that_present_priorities))
        return false;
      if (!this.priorities.equals(that.priorities))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  @Override
  public int compareTo(FactsetLookup other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetPriorities()).compareTo(other.isSetPriorities());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPriorities()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.priorities, other.priorities);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("FactsetLookup(");
    boolean first = true;

    sb.append("priorities:");
    if (this.priorities == null) {
      sb.append("null");
    } else {
      sb.append(this.priorities);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class FactsetLookupStandardSchemeFactory implements SchemeFactory {
    public FactsetLookupStandardScheme getScheme() {
      return new FactsetLookupStandardScheme();
    }
  }

  private static class FactsetLookupStandardScheme extends StandardScheme<FactsetLookup> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, FactsetLookup struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // PRIORITIES
            if (schemeField.type == org.apache.thrift.protocol.TType.MAP) {
              {
                org.apache.thrift.protocol.TMap _map0 = iprot.readMapBegin();
                struct.priorities = new HashMap<String,Short>(2*_map0.size);
                for (int _i1 = 0; _i1 < _map0.size; ++_i1)
                {
                  String _key2;
                  short _val3;
                  _key2 = iprot.readString();
                  _val3 = iprot.readI16();
                  struct.priorities.put(_key2, _val3);
                }
                iprot.readMapEnd();
              }
              struct.setPrioritiesIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, FactsetLookup struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.priorities != null) {
        oprot.writeFieldBegin(PRIORITIES_FIELD_DESC);
        {
          oprot.writeMapBegin(new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.STRING, org.apache.thrift.protocol.TType.I16, struct.priorities.size()));
          for (Map.Entry<String, Short> _iter4 : struct.priorities.entrySet())
          {
            oprot.writeString(_iter4.getKey());
            oprot.writeI16(_iter4.getValue());
          }
          oprot.writeMapEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class FactsetLookupTupleSchemeFactory implements SchemeFactory {
    public FactsetLookupTupleScheme getScheme() {
      return new FactsetLookupTupleScheme();
    }
  }

  private static class FactsetLookupTupleScheme extends TupleScheme<FactsetLookup> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, FactsetLookup struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetPriorities()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetPriorities()) {
        {
          oprot.writeI32(struct.priorities.size());
          for (Map.Entry<String, Short> _iter5 : struct.priorities.entrySet())
          {
            oprot.writeString(_iter5.getKey());
            oprot.writeI16(_iter5.getValue());
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, FactsetLookup struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        {
          org.apache.thrift.protocol.TMap _map6 = new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.STRING, org.apache.thrift.protocol.TType.I16, iprot.readI32());
          struct.priorities = new HashMap<String,Short>(2*_map6.size);
          for (int _i7 = 0; _i7 < _map6.size; ++_i7)
          {
            String _key8;
            short _val9;
            _key8 = iprot.readString();
            _val9 = iprot.readI16();
            struct.priorities.put(_key8, _val9);
          }
        }
        struct.setPrioritiesIsSet(true);
      }
    }
  }

}

