/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.ambiata.ivory.core.thrift;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class PriorityTag implements org.apache.thrift.TBase<PriorityTag, PriorityTag._Fields>, java.io.Serializable, Cloneable, Comparable<PriorityTag> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("PriorityTag");

  private static final org.apache.thrift.protocol.TField PRIORITY_FIELD_DESC = new org.apache.thrift.protocol.TField("priority", org.apache.thrift.protocol.TType.I16, (short)1);
  private static final org.apache.thrift.protocol.TField FACTBYTES_FIELD_DESC = new org.apache.thrift.protocol.TField("factbytes", org.apache.thrift.protocol.TType.STRING, (short)2);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new PriorityTagStandardSchemeFactory());
    schemes.put(TupleScheme.class, new PriorityTagTupleSchemeFactory());
  }

  public short priority; // required
  public ByteBuffer factbytes; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    PRIORITY((short)1, "priority"),
    FACTBYTES((short)2, "factbytes");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // PRIORITY
          return PRIORITY;
        case 2: // FACTBYTES
          return FACTBYTES;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __PRIORITY_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.PRIORITY, new org.apache.thrift.meta_data.FieldMetaData("priority", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I16)));
    tmpMap.put(_Fields.FACTBYTES, new org.apache.thrift.meta_data.FieldMetaData("factbytes", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING        , true)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(PriorityTag.class, metaDataMap);
  }

  public PriorityTag() {
  }

  public PriorityTag(
    short priority,
    ByteBuffer factbytes)
  {
    this();
    this.priority = priority;
    setPriorityIsSet(true);
    this.factbytes = factbytes;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public PriorityTag(PriorityTag other) {
    __isset_bitfield = other.__isset_bitfield;
    this.priority = other.priority;
    if (other.isSetFactbytes()) {
      this.factbytes = org.apache.thrift.TBaseHelper.copyBinary(other.factbytes);
;
    }
  }

  public PriorityTag deepCopy() {
    return new PriorityTag(this);
  }

  @Override
  public void clear() {
    setPriorityIsSet(false);
    this.priority = 0;
    this.factbytes = null;
  }

  public short getPriority() {
    return this.priority;
  }

  public PriorityTag setPriority(short priority) {
    this.priority = priority;
    setPriorityIsSet(true);
    return this;
  }

  public void unsetPriority() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __PRIORITY_ISSET_ID);
  }

  /** Returns true if field priority is set (has been assigned a value) and false otherwise */
  public boolean isSetPriority() {
    return EncodingUtils.testBit(__isset_bitfield, __PRIORITY_ISSET_ID);
  }

  public void setPriorityIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __PRIORITY_ISSET_ID, value);
  }

  public byte[] getFactbytes() {
    setFactbytes(org.apache.thrift.TBaseHelper.rightSize(factbytes));
    return factbytes == null ? null : factbytes.array();
  }

  public ByteBuffer bufferForFactbytes() {
    return factbytes;
  }

  public PriorityTag setFactbytes(byte[] factbytes) {
    setFactbytes(factbytes == null ? (ByteBuffer)null : ByteBuffer.wrap(factbytes));
    return this;
  }

  public PriorityTag setFactbytes(ByteBuffer factbytes) {
    this.factbytes = factbytes;
    return this;
  }

  public void unsetFactbytes() {
    this.factbytes = null;
  }

  /** Returns true if field factbytes is set (has been assigned a value) and false otherwise */
  public boolean isSetFactbytes() {
    return this.factbytes != null;
  }

  public void setFactbytesIsSet(boolean value) {
    if (!value) {
      this.factbytes = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case PRIORITY:
      if (value == null) {
        unsetPriority();
      } else {
        setPriority((Short)value);
      }
      break;

    case FACTBYTES:
      if (value == null) {
        unsetFactbytes();
      } else {
        setFactbytes((ByteBuffer)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case PRIORITY:
      return Short.valueOf(getPriority());

    case FACTBYTES:
      return getFactbytes();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case PRIORITY:
      return isSetPriority();
    case FACTBYTES:
      return isSetFactbytes();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof PriorityTag)
      return this.equals((PriorityTag)that);
    return false;
  }

  public boolean equals(PriorityTag that) {
    if (that == null)
      return false;

    boolean this_present_priority = true;
    boolean that_present_priority = true;
    if (this_present_priority || that_present_priority) {
      if (!(this_present_priority && that_present_priority))
        return false;
      if (this.priority != that.priority)
        return false;
    }

    boolean this_present_factbytes = true && this.isSetFactbytes();
    boolean that_present_factbytes = true && that.isSetFactbytes();
    if (this_present_factbytes || that_present_factbytes) {
      if (!(this_present_factbytes && that_present_factbytes))
        return false;
      if (!this.factbytes.equals(that.factbytes))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  @Override
  public int compareTo(PriorityTag other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetPriority()).compareTo(other.isSetPriority());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPriority()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.priority, other.priority);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetFactbytes()).compareTo(other.isSetFactbytes());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetFactbytes()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.factbytes, other.factbytes);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("PriorityTag(");
    boolean first = true;

    sb.append("priority:");
    sb.append(this.priority);
    first = false;
    if (!first) sb.append(", ");
    sb.append("factbytes:");
    if (this.factbytes == null) {
      sb.append("null");
    } else {
      org.apache.thrift.TBaseHelper.toString(this.factbytes, sb);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class PriorityTagStandardSchemeFactory implements SchemeFactory {
    public PriorityTagStandardScheme getScheme() {
      return new PriorityTagStandardScheme();
    }
  }

  private static class PriorityTagStandardScheme extends StandardScheme<PriorityTag> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, PriorityTag struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // PRIORITY
            if (schemeField.type == org.apache.thrift.protocol.TType.I16) {
              struct.priority = iprot.readI16();
              struct.setPriorityIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // FACTBYTES
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.factbytes = iprot.readBinary();
              struct.setFactbytesIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, PriorityTag struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(PRIORITY_FIELD_DESC);
      oprot.writeI16(struct.priority);
      oprot.writeFieldEnd();
      if (struct.factbytes != null) {
        oprot.writeFieldBegin(FACTBYTES_FIELD_DESC);
        oprot.writeBinary(struct.factbytes);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class PriorityTagTupleSchemeFactory implements SchemeFactory {
    public PriorityTagTupleScheme getScheme() {
      return new PriorityTagTupleScheme();
    }
  }

  private static class PriorityTagTupleScheme extends TupleScheme<PriorityTag> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, PriorityTag struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetPriority()) {
        optionals.set(0);
      }
      if (struct.isSetFactbytes()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetPriority()) {
        oprot.writeI16(struct.priority);
      }
      if (struct.isSetFactbytes()) {
        oprot.writeBinary(struct.factbytes);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, PriorityTag struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.priority = iprot.readI16();
        struct.setPriorityIsSet(true);
      }
      if (incoming.get(1)) {
        struct.factbytes = iprot.readBinary();
        struct.setFactbytesIsSet(true);
      }
    }
  }

}

