/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.ambiata.ivory.core.thrift;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum ThriftDictionaryEncoding implements org.apache.thrift.TEnum {
  BOOLEAN(0),
  INT(1),
  LONG(2),
  DOUBLE(3),
  STRING(4);

  private final int value;

  private ThriftDictionaryEncoding(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static ThriftDictionaryEncoding findByValue(int value) { 
    switch (value) {
      case 0:
        return BOOLEAN;
      case 1:
        return INT;
      case 2:
        return LONG;
      case 3:
        return DOUBLE;
      case 4:
        return STRING;
      default:
        return null;
    }
  }
}
