/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.ambiata.ivory.core.thrift;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class ThriftDictionary implements org.apache.thrift.TBase<ThriftDictionary, ThriftDictionary._Fields>, java.io.Serializable, Cloneable, Comparable<ThriftDictionary> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("ThriftDictionary");

  private static final org.apache.thrift.protocol.TField META_FIELD_DESC = new org.apache.thrift.protocol.TField("meta", org.apache.thrift.protocol.TType.MAP, (short)1);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new ThriftDictionaryStandardSchemeFactory());
    schemes.put(TupleScheme.class, new ThriftDictionaryTupleSchemeFactory());
  }

  public Map<ThriftDictionaryFeatureId,ThriftDictionaryFeatureMeta> meta; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    META((short)1, "meta");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // META
          return META;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.META, new org.apache.thrift.meta_data.FieldMetaData("meta", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.MapMetaData(org.apache.thrift.protocol.TType.MAP, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, ThriftDictionaryFeatureId.class), 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, ThriftDictionaryFeatureMeta.class))));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(ThriftDictionary.class, metaDataMap);
  }

  public ThriftDictionary() {
  }

  public ThriftDictionary(
    Map<ThriftDictionaryFeatureId,ThriftDictionaryFeatureMeta> meta)
  {
    this();
    this.meta = meta;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public ThriftDictionary(ThriftDictionary other) {
    if (other.isSetMeta()) {
      Map<ThriftDictionaryFeatureId,ThriftDictionaryFeatureMeta> __this__meta = new HashMap<ThriftDictionaryFeatureId,ThriftDictionaryFeatureMeta>(other.meta.size());
      for (Map.Entry<ThriftDictionaryFeatureId, ThriftDictionaryFeatureMeta> other_element : other.meta.entrySet()) {

        ThriftDictionaryFeatureId other_element_key = other_element.getKey();
        ThriftDictionaryFeatureMeta other_element_value = other_element.getValue();

        ThriftDictionaryFeatureId __this__meta_copy_key = new ThriftDictionaryFeatureId(other_element_key);

        ThriftDictionaryFeatureMeta __this__meta_copy_value = new ThriftDictionaryFeatureMeta(other_element_value);

        __this__meta.put(__this__meta_copy_key, __this__meta_copy_value);
      }
      this.meta = __this__meta;
    }
  }

  public ThriftDictionary deepCopy() {
    return new ThriftDictionary(this);
  }

  @Override
  public void clear() {
    this.meta = null;
  }

  public int getMetaSize() {
    return (this.meta == null) ? 0 : this.meta.size();
  }

  public void putToMeta(ThriftDictionaryFeatureId key, ThriftDictionaryFeatureMeta val) {
    if (this.meta == null) {
      this.meta = new HashMap<ThriftDictionaryFeatureId,ThriftDictionaryFeatureMeta>();
    }
    this.meta.put(key, val);
  }

  public Map<ThriftDictionaryFeatureId,ThriftDictionaryFeatureMeta> getMeta() {
    return this.meta;
  }

  public ThriftDictionary setMeta(Map<ThriftDictionaryFeatureId,ThriftDictionaryFeatureMeta> meta) {
    this.meta = meta;
    return this;
  }

  public void unsetMeta() {
    this.meta = null;
  }

  /** Returns true if field meta is set (has been assigned a value) and false otherwise */
  public boolean isSetMeta() {
    return this.meta != null;
  }

  public void setMetaIsSet(boolean value) {
    if (!value) {
      this.meta = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case META:
      if (value == null) {
        unsetMeta();
      } else {
        setMeta((Map<ThriftDictionaryFeatureId,ThriftDictionaryFeatureMeta>)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case META:
      return getMeta();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case META:
      return isSetMeta();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof ThriftDictionary)
      return this.equals((ThriftDictionary)that);
    return false;
  }

  public boolean equals(ThriftDictionary that) {
    if (that == null)
      return false;

    boolean this_present_meta = true && this.isSetMeta();
    boolean that_present_meta = true && that.isSetMeta();
    if (this_present_meta || that_present_meta) {
      if (!(this_present_meta && that_present_meta))
        return false;
      if (!this.meta.equals(that.meta))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  @Override
  public int compareTo(ThriftDictionary other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetMeta()).compareTo(other.isSetMeta());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetMeta()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.meta, other.meta);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("ThriftDictionary(");
    boolean first = true;

    sb.append("meta:");
    if (this.meta == null) {
      sb.append("null");
    } else {
      sb.append(this.meta);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class ThriftDictionaryStandardSchemeFactory implements SchemeFactory {
    public ThriftDictionaryStandardScheme getScheme() {
      return new ThriftDictionaryStandardScheme();
    }
  }

  private static class ThriftDictionaryStandardScheme extends StandardScheme<ThriftDictionary> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, ThriftDictionary struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // META
            if (schemeField.type == org.apache.thrift.protocol.TType.MAP) {
              {
                org.apache.thrift.protocol.TMap _map8 = iprot.readMapBegin();
                struct.meta = new HashMap<ThriftDictionaryFeatureId,ThriftDictionaryFeatureMeta>(2*_map8.size);
                for (int _i9 = 0; _i9 < _map8.size; ++_i9)
                {
                  ThriftDictionaryFeatureId _key10;
                  ThriftDictionaryFeatureMeta _val11;
                  _key10 = new ThriftDictionaryFeatureId();
                  _key10.read(iprot);
                  _val11 = new ThriftDictionaryFeatureMeta();
                  _val11.read(iprot);
                  struct.meta.put(_key10, _val11);
                }
                iprot.readMapEnd();
              }
              struct.setMetaIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, ThriftDictionary struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.meta != null) {
        oprot.writeFieldBegin(META_FIELD_DESC);
        {
          oprot.writeMapBegin(new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.STRUCT, org.apache.thrift.protocol.TType.STRUCT, struct.meta.size()));
          for (Map.Entry<ThriftDictionaryFeatureId, ThriftDictionaryFeatureMeta> _iter12 : struct.meta.entrySet())
          {
            _iter12.getKey().write(oprot);
            _iter12.getValue().write(oprot);
          }
          oprot.writeMapEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class ThriftDictionaryTupleSchemeFactory implements SchemeFactory {
    public ThriftDictionaryTupleScheme getScheme() {
      return new ThriftDictionaryTupleScheme();
    }
  }

  private static class ThriftDictionaryTupleScheme extends TupleScheme<ThriftDictionary> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, ThriftDictionary struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetMeta()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetMeta()) {
        {
          oprot.writeI32(struct.meta.size());
          for (Map.Entry<ThriftDictionaryFeatureId, ThriftDictionaryFeatureMeta> _iter13 : struct.meta.entrySet())
          {
            _iter13.getKey().write(oprot);
            _iter13.getValue().write(oprot);
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, ThriftDictionary struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        {
          org.apache.thrift.protocol.TMap _map14 = new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.STRUCT, org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
          struct.meta = new HashMap<ThriftDictionaryFeatureId,ThriftDictionaryFeatureMeta>(2*_map14.size);
          for (int _i15 = 0; _i15 < _map14.size; ++_i15)
          {
            ThriftDictionaryFeatureId _key16;
            ThriftDictionaryFeatureMeta _val17;
            _key16 = new ThriftDictionaryFeatureId();
            _key16.read(iprot);
            _val17 = new ThriftDictionaryFeatureMeta();
            _val17.read(iprot);
            struct.meta.put(_key16, _val17);
          }
        }
        struct.setMetaIsSet(true);
      }
    }
  }

}

