/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.ambiata.ivory.ingest;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class FeatureIdReducerLookup implements org.apache.thrift.TBase<FeatureIdReducerLookup, FeatureIdReducerLookup._Fields>, java.io.Serializable, Cloneable, Comparable<FeatureIdReducerLookup> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("FeatureIdReducerLookup");

  private static final org.apache.thrift.protocol.TField TO_FEATURE_ID_REDUCER_FIELD_DESC = new org.apache.thrift.protocol.TField("toFeatureIdReducer", org.apache.thrift.protocol.TType.MAP, (short)1);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new FeatureIdReducerLookupStandardSchemeFactory());
    schemes.put(TupleScheme.class, new FeatureIdReducerLookupTupleSchemeFactory());
  }

  public Map<Integer,Integer> toFeatureIdReducer; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    TO_FEATURE_ID_REDUCER((short)1, "toFeatureIdReducer");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // TO_FEATURE_ID_REDUCER
          return TO_FEATURE_ID_REDUCER;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.TO_FEATURE_ID_REDUCER, new org.apache.thrift.meta_data.FieldMetaData("toFeatureIdReducer", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.MapMetaData(org.apache.thrift.protocol.TType.MAP, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32), 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32))));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(FeatureIdReducerLookup.class, metaDataMap);
  }

  public FeatureIdReducerLookup() {
  }

  public FeatureIdReducerLookup(
    Map<Integer,Integer> toFeatureIdReducer)
  {
    this();
    this.toFeatureIdReducer = toFeatureIdReducer;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public FeatureIdReducerLookup(FeatureIdReducerLookup other) {
    if (other.isSetToFeatureIdReducer()) {
      Map<Integer,Integer> __this__toFeatureIdReducer = new HashMap<Integer,Integer>(other.toFeatureIdReducer);
      this.toFeatureIdReducer = __this__toFeatureIdReducer;
    }
  }

  public FeatureIdReducerLookup deepCopy() {
    return new FeatureIdReducerLookup(this);
  }

  @Override
  public void clear() {
    this.toFeatureIdReducer = null;
  }

  public int getToFeatureIdReducerSize() {
    return (this.toFeatureIdReducer == null) ? 0 : this.toFeatureIdReducer.size();
  }

  public void putToToFeatureIdReducer(int key, int val) {
    if (this.toFeatureIdReducer == null) {
      this.toFeatureIdReducer = new HashMap<Integer,Integer>();
    }
    this.toFeatureIdReducer.put(key, val);
  }

  public Map<Integer,Integer> getToFeatureIdReducer() {
    return this.toFeatureIdReducer;
  }

  public FeatureIdReducerLookup setToFeatureIdReducer(Map<Integer,Integer> toFeatureIdReducer) {
    this.toFeatureIdReducer = toFeatureIdReducer;
    return this;
  }

  public void unsetToFeatureIdReducer() {
    this.toFeatureIdReducer = null;
  }

  /** Returns true if field toFeatureIdReducer is set (has been assigned a value) and false otherwise */
  public boolean isSetToFeatureIdReducer() {
    return this.toFeatureIdReducer != null;
  }

  public void setToFeatureIdReducerIsSet(boolean value) {
    if (!value) {
      this.toFeatureIdReducer = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case TO_FEATURE_ID_REDUCER:
      if (value == null) {
        unsetToFeatureIdReducer();
      } else {
        setToFeatureIdReducer((Map<Integer,Integer>)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case TO_FEATURE_ID_REDUCER:
      return getToFeatureIdReducer();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case TO_FEATURE_ID_REDUCER:
      return isSetToFeatureIdReducer();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof FeatureIdReducerLookup)
      return this.equals((FeatureIdReducerLookup)that);
    return false;
  }

  public boolean equals(FeatureIdReducerLookup that) {
    if (that == null)
      return false;

    boolean this_present_toFeatureIdReducer = true && this.isSetToFeatureIdReducer();
    boolean that_present_toFeatureIdReducer = true && that.isSetToFeatureIdReducer();
    if (this_present_toFeatureIdReducer || that_present_toFeatureIdReducer) {
      if (!(this_present_toFeatureIdReducer && that_present_toFeatureIdReducer))
        return false;
      if (!this.toFeatureIdReducer.equals(that.toFeatureIdReducer))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  @Override
  public int compareTo(FeatureIdReducerLookup other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetToFeatureIdReducer()).compareTo(other.isSetToFeatureIdReducer());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetToFeatureIdReducer()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.toFeatureIdReducer, other.toFeatureIdReducer);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("FeatureIdReducerLookup(");
    boolean first = true;

    sb.append("toFeatureIdReducer:");
    if (this.toFeatureIdReducer == null) {
      sb.append("null");
    } else {
      sb.append(this.toFeatureIdReducer);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class FeatureIdReducerLookupStandardSchemeFactory implements SchemeFactory {
    public FeatureIdReducerLookupStandardScheme getScheme() {
      return new FeatureIdReducerLookupStandardScheme();
    }
  }

  private static class FeatureIdReducerLookupStandardScheme extends StandardScheme<FeatureIdReducerLookup> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, FeatureIdReducerLookup struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // TO_FEATURE_ID_REDUCER
            if (schemeField.type == org.apache.thrift.protocol.TType.MAP) {
              {
                org.apache.thrift.protocol.TMap _map10 = iprot.readMapBegin();
                struct.toFeatureIdReducer = new HashMap<Integer,Integer>(2*_map10.size);
                for (int _i11 = 0; _i11 < _map10.size; ++_i11)
                {
                  int _key12;
                  int _val13;
                  _key12 = iprot.readI32();
                  _val13 = iprot.readI32();
                  struct.toFeatureIdReducer.put(_key12, _val13);
                }
                iprot.readMapEnd();
              }
              struct.setToFeatureIdReducerIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, FeatureIdReducerLookup struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.toFeatureIdReducer != null) {
        oprot.writeFieldBegin(TO_FEATURE_ID_REDUCER_FIELD_DESC);
        {
          oprot.writeMapBegin(new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.I32, org.apache.thrift.protocol.TType.I32, struct.toFeatureIdReducer.size()));
          for (Map.Entry<Integer, Integer> _iter14 : struct.toFeatureIdReducer.entrySet())
          {
            oprot.writeI32(_iter14.getKey());
            oprot.writeI32(_iter14.getValue());
          }
          oprot.writeMapEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class FeatureIdReducerLookupTupleSchemeFactory implements SchemeFactory {
    public FeatureIdReducerLookupTupleScheme getScheme() {
      return new FeatureIdReducerLookupTupleScheme();
    }
  }

  private static class FeatureIdReducerLookupTupleScheme extends TupleScheme<FeatureIdReducerLookup> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, FeatureIdReducerLookup struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetToFeatureIdReducer()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetToFeatureIdReducer()) {
        {
          oprot.writeI32(struct.toFeatureIdReducer.size());
          for (Map.Entry<Integer, Integer> _iter15 : struct.toFeatureIdReducer.entrySet())
          {
            oprot.writeI32(_iter15.getKey());
            oprot.writeI32(_iter15.getValue());
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, FeatureIdReducerLookup struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        {
          org.apache.thrift.protocol.TMap _map16 = new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.I32, org.apache.thrift.protocol.TType.I32, iprot.readI32());
          struct.toFeatureIdReducer = new HashMap<Integer,Integer>(2*_map16.size);
          for (int _i17 = 0; _i17 < _map16.size; ++_i17)
          {
            int _key18;
            int _val19;
            _key18 = iprot.readI32();
            _val19 = iprot.readI32();
            struct.toFeatureIdReducer.put(_key18, _val19);
          }
        }
        struct.setToFeatureIdReducerIsSet(true);
      }
    }
  }

}

